- name: devops course information
  hosts: local
  connection: local
  vars:
    course: "DevOps with AWS" #String
    duration: 120 #number
    topics:
    - Linux
    - Shell
    - Ansible
    - Terraform
    - AWS
    - K8S
    live: true #boolean
    tools: #map /dictionary
      ci: jenkins
      cm: 