- name: create ec2 and r53 records
  hosts: local 
  connection: local
  vars:
    subnet_id: subnet-06ce125c8e52b13bb
    sg_id: "sg-0b7d21e84c9923e9e"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: srinivasak.online
  tasks: 
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     vpc_subnet_id: "{{ subnet_id }}"
     instance_type: "t3.micro"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
    
#private IP R53
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.srinivasak.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

#Public IP r53 record for frontend
  - name: create r53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #srinivasak.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"  

  
